### ISSUE TITLE
No te hace falta hacer .str

### ISSUE THREAD

**Issue by Javierfs94** [alvaroolt/PrimerosPOO#1]
https://github.com/alvaroolt/PrimerosPOO/blob/aa5fe9f79b423ebff98ca97bdf4ebe72b9d79c1b/PrimerosPOO/Cuadrado.py#L35

Quedaría así;  print(cuadrado1)

**Comment by alvaroolt** [comment]
Corregido! Muchas gracias @Javierfs94
